name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for git blame

      - uses: cachix/git-blame-auto-reviewer@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max-reviewers: 3
          threshold: 20
